# GolangCI-Lint configuration
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  disable:
    - depguard
  exclusions:
    # Don't run errcheck on test files
    rules:
      - linters:
          - errcheck
        path: "(.+)_test\\.go"
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (io.Closer).Close
    govet:
      enable-all: true
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
