# GolangCI-Lint configuration
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  disable:
    - depguard
  exclusions:
    rules:
      # Don't run errcheck on test files
      - linters:
          - errcheck
        path: "(.+)_test\\.go"
      # Allow unused writes in test files (test fixtures)
      - linters:
          - govet
        path: "(.+)_test\\.go"
        text: "unusedwrite"
  settings:
    errcheck:
      check-type-assertions: true
      exclude-functions:
        - (io.Closer).Close
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Too pedantic, micro-optimization
    gocyclo:
      min-complexity: 15
    misspell:
      locale: US
