# GolangCI-Lint configuration
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: standard
  disable:
    - depguard

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - govet
